### PR TITLE
Adding myself to about

### PR DESCRIPTION
**Pull request by thybag**
Hopefully text isn't to terrible, writing bio-thingys is hard.

### CODE REVIEW

**Comment by jewel-andraia** [comment]
Oxford comma?

**Comment by Ajedi32** [comment]
He meant changing "bug fixing, new features and an unhealthy amount of mediahosts" to "bug fixing, new features, and an unhealthy amount of mediahosts".

See https://en.wikipedia.org/wiki/Serial_comma

See also [this comic](http://i3.kym-cdn.com/entries/icons/original/000/017/771/the-oxford-comma_52c855ed979ed_w1500.jpg). 😜

**Comment by thybag** [comment]
Ah :p Thanks @Ajedi32 - Am I right in thinking the comma I did remove was superfluous anyway? (or should i add it back)

**Comment by Ajedi32** [comment]
Nope, I agree that the comma you removed in b7ffbb0 wasn't really needed.

**Comment by thybag** [comment]
\o/

**Pull request merged**
