### PR TITLE
Because urls should be clickable.

### PR DESCRIPTION
**Pull request by creesch**
I am helping?

### CODE REVIEW

**Comment by honestbleeps** [comment]
i think this page isn't meant to be a dumping ground of links, so those were just pasted there "for copying stuff in from them later", but I could be wrong.. I defer to the powers that be :)

**Comment by creesch** [comment]
yeah I figured, also figured it is easier to copy over if you can just go there by clicking :P

**Comment by jewel-andraia** [comment]
I wonder what would happen if you renamed (the current master version) to `wiki.md`

**Comment by erikdesjardins** [comment]
> renamed (the current master version) to wiki.md

This works, and is better (if we want to make these clickable, but this page is probably just going to be removed/replaced soon)

**Pull request closed without merging**
